### ISSUE TITLE
Issue to retrieve data

### ISSUE THREAD

**Issue by Lumiahna** [kirstystroud/wow-guild-page#3]
Hello,
I've got an issue while doing a /getall from my win10 locally

`
  [GuzzleHttp\Exception\ClientException]
  Client error: `GET https://eu.battle.net/oauth/token?grant_type=client_credentials` resulted in a `401 Unauthorized
  ` response:
  {"error":"unauthorized","error_description":"Bad credentials"}

Loading characters
Loading ilvls
    0 [>---------------------------]
Loading titles
    0 [>---------------------------]
Loading reputation
    0 [>---------------------------]
Loding raids
    0 [>---------------------------]
Loading professions
    0 [>---------------------------]
Loading statistics
    0 [>---------------------------]
Loading achievements
    0 [>---------------------------]
Loading quests
    0 [>---------------------------]
Loading pets
    0 [>---------------------------]
Loading auctions
Loading file

  [GuzzleHttp\Exception\ClientException]
  Client error: `GET https://eu.battle.net/oauth/token?grant_type=client_credentials` resulted in a `401 Unauthorized
  ` response:
  {"error":"unauthorized","error_description":"Bad credentials"}
`

My credits are right Idk where I messed up.
Cheers

**Comment by kirstystroud** [comment]
Hi, thanks for bringing this up. This was due to an inconsistency between `.env.example` and the Guzzle authentication setup - the above commit should have resolved this (no `.env` changes required)
